# This message is used to specify rectangle with face and name of person

uint32 x  		# UpperLeft x coordination of face
uint32 y  		# UpperLeft y coordination of face
uint32 h  		# Height of face
uint32 w  		# Width of face

string name			# Name of face owner

bool found_logo 	# bool if logo was found_logo
uint32 logo_x  		# UpperLeft x coordination of logo
uint32 logo_y  		# UpperLeft y coordination of logo
uint32 logo_h  		# Height of logo
uint32 logo_w  		# Width of logo
